name: filehive
description: "Offline peer-to-peer file transfer application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.3.1

  # Navigation
  go_router: ^17.2.1

  # Networking
  dio: ^5.9.0
  connectivity_plus: ^7.0.0
  network_info_plus: ^7.0.0

  # Device Discovery
  multicast_dns: ^0.3.3
  nsd: ^4.0.3

  # Local Server
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  shelf_multipart: ^1.0.0
  http_parser: ^4.1.2

  # File Management
  file_picker: ^10.3.2
  path_provider: ^2.1.5
  path: ^1.9.1

  # Permissions
  permission_handler: ^12.0.1

  # Utilities
  crypto: ^3.0.6
  uuid: ^4.5.1

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
